env_path = ".env"

name = "nexus-auth-service"
main = "src/index.js"              # Entry file for your Worker
compatibility_date = "2025-09-17"  # Can be today's date or newer

# âœ… Ensure Wrangler uses modules mode and bundles npm deps
compatibility_flags = ["nodejs_compat"]

[vars]
JWT_SECRET = "your-very-long-random-secret"

[[d1_databases]]
binding = "DB"
database_name = "nexus-users-db"
database_id = "a6b8cb04-f731-4852-a636-fc47ca28367d"
ECHO is on.
